event_store:
  image: eventstore/eventstore
  ports:
    - 2113:2113
    - 1113:1113
  environment:
    EVENTSTORE_START_STANDARD_PROJECTIONS: "True"
    EVENTSTORE_RUN_PROJECTIONS: "all"

read_database:
  image: postgres
  ports:
    - 5432:5432

